### PR TITLE
feat : have multiple flavours for testing purposes

### LINKED ISSUE #16: Create a test variant of the app
Create a test variant where anyone is able to push/delete data.

### PR DESCRIPTION
**Pull request by the-dagger**
fix #16 
Created a new product variant and linked a new firebase project with it that allows full read and write to all the authenticated users.
@gogeta95 Try to setup the project on your machine to check if it works, I'll add you as a contributor to the new project.
@gogeta95 Also please squash the commits instead of directly merging.

### CODE REVIEW

**Comment by the-dagger** [comment]
Turns out that noting is getting written to the sharedpreferences, so need to work a bit more on this.

**Comment by the-dagger** [comment]
@gogeta95 squashed all commits into one

**Comment by the-dagger** [comment]
Notifications are also getting displayed at an interval of 1.5 - 2 hours

**Comment by gogeta95** [comment]
@the-dagger is anyone is able to add or remove data in demo code, whats the purpose of specifying admin emails in there?

**Comment by gogeta95** [comment]
also there is a  lot of code being duplicated in prod and demo flavor, needs to be removed.

**Comment by the-dagger** [comment]
@gogeta95 yeah anyone is able ye remove and add data , and I haven't specified the emails anywhere in there.

**Comment by the-dagger** [comment]
It seems like the adapted file is duplicated in both, which I'll fix in a min.

**Comment by gogeta95** [comment]
My bad, i implemented new auth which need not to specify emails and is hasn't been merged yet.

**Comment by the-dagger** [comment]
@gogeta95 fixed it , please have a look at it now

**Comment by gogeta95** [comment]
Awesome, this is perfect!

**Review by gogeta95 — APPROVED** [review]
Perfect. flavors implemented correctly.

**Pull request merged**
